// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB00bdVgZAVrAVlJduk5Fv6PF6sNq4T1fM',
    appId: '1:1097761824620:web:1892e9ad072b4800721d49',
    messagingSenderId: '1097761824620',
    projectId: 'restauapp-dee72',
    authDomain: 'restauapp-dee72.firebaseapp.com',
    storageBucket: 'restauapp-dee72.firebasestorage.app',
    measurementId: 'G-CVQLE8FRF3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDV8ClfV961ouRUkRPYrelogVtne3d7LfQ',
    appId: '1:1097761824620:android:07ee6bef2758a13e721d49',
    messagingSenderId: '1097761824620',
    projectId: 'restauapp-dee72',
    storageBucket: 'restauapp-dee72.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8ypwV3Bv88e4I46Culd0NKCIyR_s9krE',
    appId: '1:1097761824620:ios:d41b293d3edee509721d49',
    messagingSenderId: '1097761824620',
    projectId: 'restauapp-dee72',
    storageBucket: 'restauapp-dee72.firebasestorage.app',
    iosBundleId: 'com.example.pageinscripcription',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8ypwV3Bv88e4I46Culd0NKCIyR_s9krE',
    appId: '1:1097761824620:ios:d41b293d3edee509721d49',
    messagingSenderId: '1097761824620',
    projectId: 'restauapp-dee72',
    storageBucket: 'restauapp-dee72.firebasestorage.app',
    iosBundleId: 'com.example.pageinscripcription',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB00bdVgZAVrAVlJduk5Fv6PF6sNq4T1fM',
    appId: '1:1097761824620:web:684e571db78e1407721d49',
    messagingSenderId: '1097761824620',
    projectId: 'restauapp-dee72',
    authDomain: 'restauapp-dee72.firebaseapp.com',
    storageBucket: 'restauapp-dee72.firebasestorage.app',
    measurementId: 'G-SGW95K34HS',
  );
}
